# Backend Service Makefile

.PHONY: help
help: ## Show this help message
	@echo 'Backend E2E Test Commands:'
	@echo ''
	@echo '  make test-e2e  - Run E2E integration tests'
	@echo ''

.PHONY: test-e2e
test-e2e: ## Run E2E integration tests
	@echo "Running E2E integration tests..."
	@./scripts/test-integration.sh