name: PR Lint

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'apps/frontend/**'
      - '.github/workflows/pr-lint.yml'

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint Frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'apps/frontend/package-lock.json'

      - name: Install dependencies
        working-directory: ./apps/frontend
        run: npm ci

      - name: Run ESLint
        working-directory: ./apps/frontend
        run: npm run lint

      - name: Run Stylelint
        working-directory: ./apps/frontend
        run: npm run stylelint