name: Production

on:
  push:
    branches: [ main ]
    paths:
      - 'terraform/**'
      - 'apps/backend/**'
      - 'apps/billing/**'
      - 'apps/frontend/**'
      - '.github/workflows/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'terraform/**'
      - 'apps/backend/**'
      - 'apps/billing/**'
      - 'apps/frontend/**'
  workflow_dispatch:

jobs:
  deploy:
    uses: ./.github/workflows/deploy.yml
    with:
      deploy_environment: production
    secrets: inherit