name: Staging

on:
  workflow_dispatch:

jobs:
  deploy:
    uses: ./.github/workflows/deploy.yml
    with:
      environment: staging
      service_suffix: -staging
      terraform_workspace: staging
    secrets: inherit